#!/bin/sh

bspc config split_ratio 0.5
bspc config history_aware_focus true
bspc config focus_by_distance true
bspc config borderless_monocle false
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config auto_alternate true
bspc config auto_cancel true
bspc config window_gap 12
bspc config border_width 0
bspc config top_padding 24

bspc rule -a "Steam" floating=on
bspc rule -a "Skype" floating=on
bspc rule -a "Thunar" floating=on
bspc rule -a "Toplevel" floating=on

bspc monitor -d 1 2 3 4


xss-lock -- /home/brandon/.bin/lock.sh &
compton -b
urxvt -name '- - -' & sleep 0.5; killall urxvt
~/.bin/panel/panel.sh

